spring:
  profiles:
    active: local
---
server:
  port: 8080
  host:
    front: localhost8080
spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE_NAME}

    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 10
      max-lifetime: 240000
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  sql:
    init:
      mode: never

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

cloud: # S3
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      url: ${S3_URL}
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false

payment:
  toss:
    client-key: ${TOSS_CLIENT_KEY}
    secret-key: ${TOSS_SECRET_KEY}
    success-url: ${SUCCESS_URL}
    fail-url: ${FAIL_URL}